### ISSUE TITLE
Typescript Declarations

### ISSUE THREAD

**Issue by kaaax0815** [khalby786/jsoning#14]
**Is your feature request related to a problem? Please describe.**
I want to use your package in a Typescript project

**Describe the solution you'd like**
Add Typings for jsoning

**Describe alternatives you've considered**
Only alternative would be using another package

**Comment by khalby786** [comment]
Update to v0.11.21, let me know if it works!

https://github.com/khalby786/jsoning/commit/bfb93967ee865771d4592f42f0f3b61762ca5f46
