### ISSUE TITLE
set(key, value) does not read the DB from the file system and overwrites file system changes

### ISSUE THREAD

**Issue by manmal** [khalby786/jsoning#16]
## Describe the bug
If jsoning has written at least one value, and the json file is changed in the file system by a different process, and then `set()` is called with some value, then jsoning overwrites the json file with the previously known values.

## Reproducible code sample (if applicable)

```javascript
let db = new jsoning("database.json");
db.set("one", "one");
// Now remove database.json from the file system
db.set("two", "two");
```

## Expected behavior

After executing the sample code (note the comment about removing the file), the expected behavior would be that database.json contains `{"two": "two"}`. 

Faulty behavior: The database.json contains `{"one": "one", "two": "two"}`.

## Further details
- Jsoning version: 0.11.21
- Node.js version: v14.17.1
- Operating system: macOS 11.2.3

**Comment by khalby786** [comment]
This is indeed interesting, I'll take a look and see what I can do. Thanks for reporting it!

**Comment by manmal** [comment]
@khalby786 I created a PR, this fixes the issue for me
