### ISSUE TITLE
Typescript: Push method value parameter type

### ISSUE THREAD

**Issue by Kerrders** [khalby786/jsoning#21]
https://github.com/khalby786/jsoning/blob/46e0f1be579eafe61ae864c1ec90babdc307c283/src/jsoning.d.ts#L144
The type of the value parameter should be `any `because I am working with objects here and keep getting an lint error

**Comment by khalby786** [comment]
Your wish is my command 😆 

![image](https://user-images.githubusercontent.com/38468163/135710016-576ed1fc-6edf-4bf4-8109-f7c5c6058969.png)

**Comment by khalby786** [comment]
Let me know if you face any more issues!

```shell
npm i jsoning@0.12.22
```
