### ISSUE TITLE
Summing of values

### ISSUE THREAD

**Issue by Justman10000** [khalby786/jsoning#31]
## Describe the bug
Instead of summing the values, the new values are simply appended to the existing value!

Example:
We have the value 25 and want to add it to 25, which would actually be 50, but the result is 2525!
<br>

## Further details
- Jsoning version: 0.13.23
- Node.js version: 16.18.1
- Operating system: Microsoft Windows 11 Pro

**Comment by khalby786** [comment]
Hi, could you please provide some reproducible code? Thanks!

**Comment by Justman10000** [comment]
```javascript
coins.math(interaction.member.user.id, "add", earnRandomCoins())
```

```javascript
const coins = [
  "25",
  "50",
  "100",
  "150",
  "250",
  "500",
  "750",
  "1000"
];
const percentages = [
  80,
  70,
  50,
  40,
  20,
  10,
  10,
  5
];

function earnRandomCoins() {
  const randomValue = Math.random();
  let cumulativeProbability = 0;
  
  for (let i = 0; i < percentages.length; i++) {
    const probability = percentages[i] / 100;
    cumulativeProbability += probability;
    
    if (randomValue <= cumulativeProbability) {
      return coins[i];
    }
  }
}
```

**Comment by khalby786** [comment]
>```js
>const coins = [
>	"25",
>	"50",
>	"100",
>	"150",
>	"250",
>	"500",
>	"750",
>	"1000"
>];
>```

You are providing coin values as a string. [When you add two strings in JavaScript, they get concatenated](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings#concatenation_using) even if the value is a "number".

To solve this, store your coins as numbers.

```js
const coins = [
  25,
  50,
  100,
  150,
  250,
  500,
  750,
  1000
];
```

I'm also curious whether you get an error when you execute `coins.math(interaction.member.user.id, "add", earnRandomCoins())` because there is type validation in place to make sure that you only pass a number and not a string to prevent situations like this, and the program is supposed to terminate at that error.

**Comment by Justman10000** [comment]
> > ```js
> > const coins = [
> >   "25",
> >   "50",
> >   "100",
> >   "150",
> >   "250",
> >   "500",
> >   "750",
> >   "1000"
> > ];
> > ```
> 
> You are providing coin values as a string. [When you add two strings in JavaScript, they get concatenated](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings#concatenation_using) even if the value is a "number".
> 
> To solve this, store your coins as numbers.
> 
> ```js
> const coins = [
>   25,
>   50,
>   100,
>   150,
>   250,
>   500,
>   750,
>   1000
> ];
> ```
> 
> I'm also curious whether you get an error when you execute `coins.math(interaction.member.user.id, "add", earnRandomCoins())` because there is type validation in place to make sure that you only pass a number and not a string to prevent situations like this, and the program is supposed to terminate at that error.

I no longer get any errors because I had removed the check!

**Comment by Justman10000** [comment]
Although, now comes the mistake:

> Error: Key of existing element must be a number for Jsoning#math to happen.

**Comment by Justman10000** [comment]
Although, now comes the error:

> Error: Key of existing element must be a number for Jsoning#math to happen.

**Comment by Justman10000** [comment]
Anyway, it works...

**Comment by Justman10000** [comment]
Hmm, although if by chance 50 or more coins are chosen, only 25 are credited...

**Comment by khalby786** [comment]
>```js
>function earnRandomCoins() {
>  const randomValue = Math.random();
>  let cumulativeProbability = 0;
>  
>  for (let i = 0; i < percentages.length; i++) {
>    const probability = percentages[i] / 100;
>    cumulativeProbability += probability;
>    
>    if (randomValue <= cumulativeProbability) {
>      return coins[i];
>    }
>  }
>}

Then it must be a problem with your coin logic. Afaik, `Jsoning#math` works as intended unless you can provide me with detailed reproducible examples (I will be running tests again, though)

Hope this helped!
