### ISSUE TITLE
DB entry rewrite

### ISSUE THREAD

**Issue by Justman10000** [khalby786/jsoning#32]
**Is your feature request related to a problem? Please describe.**
With `db.set(key, value)` one creates a database entry! The problem? There can only be one entry per database!

**Describe the solution you'd like**
When an entry is created, it looks like this:

`{key: value}`

If one only wants to create a new entry, this would look something like this:

```json
{
    "key1": "value1",
    "key2": "value2",
    "key3": "value3"
}
```

Of course, one could still use `db.get` and `db.has` as usual...

**Comment by khalby786** [comment]
Hi, that's intended behavior! Keys are meant to be unique!

**Comment by Justman10000** [comment]
> Hi, that's intended behavior! Keys are meant to be unique!

It is stupid to need a single DB for each entry! Let's take keyv... You can create as many tables as you want in one database! Here, you can only create and manage one table per database!

**Comment by khalby786** [comment]
keyv is a great key-value storage package for multiple backends - this package offers an interface to utilise JSON files to be able to store something for small-scale purposes and that includes making it backwards compatible with already existing JSON files.
