### ISSUE TITLE
A jsoning question - PHP related ( although this IS a npm package ) - not to the language itself

### ISSUE THREAD

**Issue by Supernova3339** [khalby786/jsoning#34]
Is it possible to include just the source file directly?
I've got a PHP project called anonupload ( supernova3339/anonupload )
The kicker is it doesn't use a database. I want to add in multi-user support and finish off plugins. Instead of going crazy, I found your kick-ass project and would like to know if this is possible.

If yes, I'll integrate your project into anonupload as a JsonDB
If no, I'll finish off what I already started.
If confused, other, whatever, feel free to ask me questions.
If implementable, I'll write code to make it possible, then I'll send a PR for said code

**Comment by khalby786** [comment]
Go ahead! Let me know if I can do anything to help. Good luck!

**Comment by Supernova3339** [comment]
> Go ahead! Let me know if I can do anything to help. Good luck!

Is this a yes, no, confused, or implementable? Confused :/

**Comment by khalby786** [comment]
Confused - where and how exactly does Jsoning fit into your PHP project?

**Comment by Supernova3339** [comment]
Jsoning would fit in as a backend DB, however I might not be able to
implement it. It's way too much dependencies.
