### ISSUE TITLE
suggestions 

### ISSUE THREAD

**Issue by DreamBoy65** [khalby786/jsoning#35]
Hello, im dream.
so i would like suggest some function and modules that you can add.

+ clone option - to clone the whole db to given path
+ events - add entry/exit/update events
+ backup - eventually update backup db

im thinking of adding these functions to your npm package so i was just asking for permission if its okay!

if its okay then i can start the code.

**Comment by DreamBoy65** [comment]
nvm

**Comment by khalby786** [comment]
It's open-source, you don't need permission! And I'd love to see what you come up with!

**Comment by khalby786** [comment]
@DreamBoy65 it's been almost a whole year, but its a feature now!

```bash
npm install jsoning@1.0.0
```

See [release notes](https://github.com/khalby786/jsoning/releases/tag/v1.0.0).

**Comment by DreamBoy65** [comment]
Thats Great to hear. Sorry i was busy with other businesses so i couldn't contribute.
