### ISSUE TITLE
Add type parameter to Jsoning class

### ISSUE THREAD

**Issue by ackledotdev** [khalby786/jsoning#36]
**Is your feature request related to a problem? Please describe.**
No problem per se

**Describe the solution you'd like**
I would like for the class to take a type parameter upon creation, restricting the database to that specific type and thus simplifying the programming.

**Describe alternatives you've considered**
I ended up doing this in my code, but it would be helpful if the class itself already accepted the type parameter.
```ts
class Database<T> extends Jsoning {
	constructor(path: string) {
		super(path);
	}

	async set(key: string, value: T): Promise<boolean> {
		return await super.set(key, value);
	}

	get(key: string): Promise<T> {
		return super.get(key);
	}

	all(): { [key: string]: T } {
		return super.all();
	}
}
```

**Additional context**
TypeScript v4.9.5

**Comment by ackledotdev** [comment]
Created a new version of this with a type parameter, see [`typed-jsoning`](https://npmjs.com/package/typed-jsoning).

**Comment by khalby786** [comment]
Jsoning now has types! (yes i know you did it lol, leaving this comment for future reference)
