### ISSUE TITLE
Exclude node_modules

### ISSUE THREAD

**Issue by amalshehu** [khalby786/jsoning#7]
It's a good practice. Add it to .gitignore

**Comment by trentwiles** [comment]
That would be a good idea.

**Comment by khalby786** [comment]
😂 It was gitignored, but I accidentally committed it.

**Comment by khalby786** [comment]
Hey @amalshehu and @RiversideRocks, 

Thanks for reporting this!

I have gitignored node_modules and removed them from the repo! This issue will be now closed.

Thanks, once again! 😅
