### ISSUE TITLE
Prototype Pollution Vulnerability

### ISSUE THREAD

**Issue by ehcac1024** [khalby786/jsoning#9]
## Describe the bug
Prototype pollution by setting a value with a key of "hasOwnProperty"

## Reproducible code sample (if applicable)

```javascript
await db.set("hasOwnProperty", "something");
await db.has("hasOwnProperty"); // Error is thrown
```

## Further details
- Jsoning version: 0.8.16

## Additional context
This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code Execution under specific circumstances.

i also already made a PR to patch this vulnerability https://github.com/khalby786/jsoning/pull/8

**Comment by ehcac1024** [comment]
Also, this vulnerability has been reported to NPM Security Team

**Comment by khalby786** [comment]
Hi @oadpoaw!

Thanks for reporting the vulnerability!

I'll be merging the pull request linked with this issue very soon. No conflicts so your PR should be good to go!

Cheers!

**Comment by khalby786** [comment]
Fixed: https://github.com/khalby786/jsoning/commit/8d17ef7f805341dcad95b4b523c3e83828a02bce
